import sys

def main():
    with open('src/utils/output.test.ts', 'w') as f:
        f.write("import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';\n")
        f.write("import { formatOutput, printOutput, printError, printSuccess, printWarning, printInfo, printTable, printProgress, printHeader, exit as e } from './output.js';\n")
        f.write("\n")
        f.write("describe('Output Utilities', () => {\n")
        f.write("  let consoleLogSpy: any;\n")
        f.write("  let consoleErrorSpy: any;\n")
        f.write("  let processExitSpy: any;\n")
        f.write("\n")
        f.write("  beforeEach(() => {\n")
        f.write("    consoleLogSpy = vi.spyOn(console, 'log').mockImplementation(() => {});\n")
        f.write("    consoleErrorSpy = vi.spyOn(console, 'error').mockImplementation(() => {});\n")
        f.write("    processExitSpy = vi.spyOn(process, 'exit').mockImplementation((() => {}) as any);\n")
        f.write("  });\n")
        f.write("\n")
        f.write("  afterEach(() => {\n")
        f.write("    vi.restoreAllMocks();\n")
        f.write("  });\n")
        f.write("\n")
        f.write("  describe('formatOutput', () => {\n")
        f.write("    it('should format as JSON when --json flag is provided', () => {\n")
        f.write("      const data = { key: 'value' };\n")
        f.write("      expect(formatOutput(data, { json: true })).toBe(JSON.stringify(data, null, 2));\n")
        f.write("    });\n")
        f.write("\n")
        f.write("    it('should format raw strings correctly in raw/silent mode', () => {\n")
        f.write("      expect(formatOutput('raw string', { raw: true })).toBe('raw string');\n")
        f.write("      expect(formatOutput('silent string', { silent: true })).toBe('silent string');\n")
        f.write("    });\n")
        f.write("\n")
        f.write("    it('should stringify objects in raw/silent mode', () => {\n")
        f.write("      const data = { key: 'value' };\n")
        f.write("      expect(formatOutput(data, { raw: true })).toBe(JSON.stringify(data));\n")
        f.write("      expect(formatOutput(data, { silent: true })).toBe(JSON.stringify(data));\n")
        f.write("    });\n")
        f.write("\n")
        f.write("    it('should return human-readable strings directly', () => {\n")
        f.write("      expect(formatOutput('human string', {})).toBe('human string');\n")
        f.write("    });\n")
        f.write("\n")
        f.write("    it('should stringify objects for human-readable mode', () => {\n")
        f.write("      const data = { key: 'value' };\n")
        f.write("      expect(formatOutput(data, {})).toBe(JSON.stringify(data, null, 2));\n")
        f.write("    });\n")
        f.write("  });\n")
        f.write("\n")
        f.write("  describe('printOutput', () => {\n")
        f.write("    it('should print formatted output to console.log', () => {\n")
        f.write("      printOutput('test message', { raw: true });\n")
        f.write("      expect(consoleLogSpy).toHaveBeenCalledWith('test message');\n")
        f.write("    });\n")
        f.write("  });\n")
        f.write("\n")
        f.write("  describe('printError', () => {\n")
        f.write("    it('should print JSON error when --json flag is true', () => {\n")
        f.write("      printError('test error', { json: true });\n")
        f.write("      expect(consoleErrorSpy).toHaveBeenCalledWith(JSON.stringify({ error: 'test error' }));\n")
        f.write("    });\n")
        f.write("\n")
        f.write("    it('should print formatted error in normal mode', () => {\n")
        f.write("      printError('test error', {});\n")
        f.write("      expect(consoleErrorSpy).toHaveBeenCalledWith(expect.stringContaining('Error:'));\n")
        f.write("      expect(consoleErrorSpy).toHaveBeenCalledWith(expect.stringContaining('test error'));\n")
        f.write("    });\n")
        f.write("\n")
        f.write("    it('should print plain error in silent/raw mode', () => {\n")
        f.write("      printError('test error', { raw: true });\n")
        f.write("      expect(consoleErrorSpy).toHaveBeenCalledWith('test error');\n")
        f.write("    });\n")
        f.write("  });\n")
        f.write("\n")
        f.write("  describe('printSuccess', () => {\n")
        f.write("    it('should print JSON success when --json flag is true', () => {\n")
        f.write("      printSuccess('test success', { json: true });\n")
        f.write("      expect(consoleLogSpy).toHaveBeenCalledWith(JSON.stringify({ success: true, message: 'test success' }));\n")
        f.write("    });\n")
        f.write("\n")
        f.write("    it('should print formatted success in normal mode', () => {\n")
        f.write("      printSuccess('test success', {});\n")
        f.write("      expect(consoleLogSpy).toHaveBeenCalledWith(expect.stringContaining('✓'));\n")
        f.write("      expect(consoleLogSpy).toHaveBeenCalledWith(expect.stringContaining('test success'));\n")
        f.write("    });\n")
        f.write("\n")
        f.write("    it('should print plain success in silent/raw mode', () => {\n")
        f.write("      printSuccess('test success', { raw: true });\n")
        f.write("      expect(consoleLogSpy).toHaveBeenCalledWith('test success');\n")
        f.write("    });\n")
        f.write("  });\n")
        f.write("\n")
        f.write("  describe('printWarning', () => {\n")
        f.write("    it('should print JSON warning when --json flag is true', () => {\n")
        f.write("      printWarning('test warning', { json: true });\n")
        f.write("      expect(consoleLogSpy).toHaveBeenCalledWith(JSON.stringify({ warning: 'test warning' }));\n")
        f.write("    });\n")
        f.write("\n")
        f.write("    it('should print formatted warning in normal mode', () => {\n")
        f.write("      printWarning('test warning', {});\n")
        f.write("      expect(consoleLogSpy).toHaveBeenCalledWith(expect.stringContaining('⚠'));\n")
        f.write("      expect(consoleLogSpy).toHaveBeenCalledWith(expect.stringContaining('test warning'));\n")
        f.write("    });\n")
        f.write("\n")
        f.write("    it('should print plain warning in silent/raw mode', () => {\n")
        f.write("      printWarning('test warning', { raw: true });\n")
        f.write("      expect(consoleLogSpy).toHaveBeenCalledWith('test warning');\n")
        f.write("    });\n")
        f.write("  });\n")
        f.write("\n")
        f.write("  describe('printInfo', () => {\n")
        f.write("    it('should print JSON info when --json flag is true', () => {\n")
        f.write("      printInfo('test info', { json: true });\n")
        f.write("      expect(consoleLogSpy).toHaveBeenCalledWith(JSON.stringify({ info: 'test info' }));\n")
        f.write("    });\n")
        f.write("\n")
        f.write("    it('should print formatted info in normal mode', () => {\n")
        f.write("      printInfo('test info', {});\n")
        f.write("      expect(consoleLogSpy).toHaveBeenCalledWith(expect.stringContaining('ℹ'));\n")
        f.write("      expect(consoleLogSpy).toHaveBeenCalledWith(expect.stringContaining('test info'));\n")
        f.write("    });\n")
        f.write("\n")
        f.write("    it('should print plain info in silent/raw mode', () => {\n")
        f.write("      printInfo('test info', { raw: true });\n")
        f.write("      expect(consoleLogSpy).toHaveBeenCalledWith('test info');\n")
        f.write("    });\n")
        f.write("  });\n")
        f.write("\n")
        f.write("  describe('printTable', () => {\n")
        f.write("    const headers = ['A', 'B'];\n")
        f.write("    const rows = [['1', '2'], ['3', '4']];\n")
        f.write("\n")
        f.write("    it('should print JSON when --json flag is true', () => {\n")
        f.write("      printTable(headers, rows, { json: true });\n")
        f.write("      expect(consoleLogSpy).toHaveBeenCalledWith(JSON.stringify({ headers, rows }));\n")
        f.write("    });\n")
        f.write("\n")
        f.write("    it('should print tab-separated values in raw/silent mode', () => {\n")
        f.write("      printTable(headers, rows, { raw: true });\n")
        f.write("      expect(consoleLogSpy).toHaveBeenCalledWith('1\\t2');\n")
        f.write("      expect(consoleLogSpy).toHaveBeenCalledWith('3\\t4');\n")
        f.write("    });\n")
        f.write("\n")
        f.write("    it('should print formatted table in normal mode', () => {\n")
        f.write("      printTable(headers, rows, {});\n")
        f.write("      // Header, separator, and 2 rows\n")
        f.write("      expect(consoleLogSpy).toHaveBeenCalledTimes(4);\n")
        f.write("      expect(consoleLogSpy.mock.calls[0][0]).toContain('A  B');\n")
        f.write("      expect(consoleLogSpy.mock.calls[1][0]).toContain('-  -');\n")
        f.write("      expect(consoleLogSpy.mock.calls[2][0]).toContain('1  2');\n")
        f.write("      expect(consoleLogSpy.mock.calls[3][0]).toContain('3  4');\n")
        f.write("    });\n")
        f.write("  });\n")
        f.write("\n")
        f.write("  describe('printProgress', () => {\n")
        f.write("    it('should not print in silent/raw mode', () => {\n")
        f.write("      printProgress('test progress', { raw: true });\n")
        f.write("      expect(consoleLogSpy).not.toHaveBeenCalled();\n")
        f.write("    });\n")
        f.write("\n")
        f.write("    it('should print formatted progress in normal mode', () => {\n")
        f.write("      printProgress('test progress', {});\n")
        f.write("      expect(consoleLogSpy).toHaveBeenCalledWith(expect.stringContaining('test progress'));\n")
        f.write("    });\n")
        f.write("  });\n")
        f.write("\n")
        f.write("  describe('printHeader', () => {\n")
        f.write("    it('should not print in silent/raw mode', () => {\n")
        f.write("      printHeader({ silent: true });\n")
        f.write("      expect(consoleLogSpy).not.toHaveBeenCalled();\n")
        f.write("    });\n")
        f.write("\n")
        f.write("    it('should print ASCII art header in normal mode', () => {\n")
        f.write("      printHeader({});\n")
        f.write("      expect(consoleLogSpy).toHaveBeenCalled();\n")
        f.write("      expect(consoleLogSpy.mock.calls[6][0]).toContain('JSON Reference CLI');\n")
        f.write("    });\n")
        f.write("  });\n")
        f.write("\n")
        f.write("  describe('exit', () => {\n")
        f.write("    it('should call process.exit with the given code', () => {\n")
        f.write("      e(42);\n")
        f.write("      expect(processExitSpy).toHaveBeenCalledWith(42);\n")
        f.write("    });\n")
        f.write("  });\n")
        f.write("});\n")

if __name__ == "__main__":
    main()
